# <font color='blue'>Numpy Refresher</font>

### <font style="color:rgb(8,133,37)">Why do we need a special library for math and DL?</font>
Python provides data types such as lists / tuples out of the box. Then, why are we using special libraries for deep learning tasks, such as Pytorch or TensorFlow, and not using standard types?

The major reason is efficiency - In pure python, there are no primitive types for numbers, as in e.g. C language. All the data types in Python are objects with lots of properties and methods. You can see it using the `dir` function:

In [1]:
a = 3
dir(a)[-10:]

['as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

### <font style="color:rgb(8,133,37)">Python Issues</font>

- slow in tasks that require tons of simple math operations on numbers
- huge memory overhead due to storing plain numbers as objects
- runtime overhead during memory dereferencing - cache issues


NumPy is an abbreviation for "numerical python" and as it stands from the naming it provides a rich collection of operations on the numerical data types with a python interface. The core data structure of NumPy is `ndarray` - a multidimensional array. Let's take a look at its interface in comparison with plain python lists.

# <font color='blue'>Performance comparison of Numpy array and Python lists </font>

Let's imagine a simple task - we have several 2-dimensional points and we want to represent them as a list of points for further processing. For the sake of simplicity of processing we will not create a `Point` object and will use a list of 2 elements to represent coordinates of each point (`x` and `y`):

In [2]:
# create points list using explicit specification of coordinates of each point
points = [[0, 1], [10, 5], [7, 3]]
points

[[0, 1], [10, 5], [7, 3]]

In [3]:
# create random points
from random import randint

num_dims = 2
num_points = 10
x_range = (0, 10)
y_range = (1, 50)
points = [[randint(*x_range), randint(*y_range)] for _ in range(num_points)]
points

[[2, 46],
 [1, 29],
 [1, 17],
 [5, 7],
 [7, 10],
 [9, 22],
 [3, 11],
 [2, 38],
 [8, 17],
 [2, 32]]

**How can we do the same using Numpy? Easy!**

In [4]:
import numpy as np
points = np.array(points)  # we are able to create numpy arrays from python lists
points

array([[ 2, 46],
       [ 1, 29],
       [ 1, 17],
       [ 5,  7],
       [ 7, 10],
       [ 9, 22],
       [ 3, 11],
       [ 2, 38],
       [ 8, 17],
       [ 2, 32]])

In [5]:
# create random points using numpy library
num_dims = 2
num_points = 10
x_range = (0, 11)
y_range = (1, 51)
points = np.random.randint(
    low=(x_range[0], y_range[0]), high=(x_range[1], y_range[1]), size=(num_points, num_dims)
)
points

array([[ 2, 27],
       [ 3, 29],
       [ 9, 37],
       [ 2, 23],
       [ 7,  6],
       [ 7,  4],
       [10, 46],
       [ 4, 17],
       [10, 31],
       [ 3, 13]])

**It may look as over-complication to use NumPy for the creation of such a list and we still cannot see the good sides of this approach. But let's take a look at the performance side.**

In [6]:
num_dims = 2
num_points = 100000
x_range = (0, 10)
y_range = (1, 50)

### <font style="color:rgb(8,133,37)">Python performance</font>

In [7]:
%timeit \
points = [[randint(*x_range), randint(*y_range)] for _ in range(num_points)]

71 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### <font style="color:rgb(8,133,37)">NumPy performance</font>

In [8]:
%timeit \
points = np.random.randint(low=(x_range[0], y_range[0]), high=(x_range[1], y_range[1]), size=(num_points, num_dims))

3.38 ms ± 33.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Wow, NumPy is **around 50 times faster** than pure Python on this task! One may say that the size of the array we're generating is relatively large, but it's very reasonable if we take into account the dimensions of inputs (and weights) in neural networks (or math problems such as hydrodynamics).

# <font style="color:blue">Basics of Numpy </font>
We will go over some of the useful operations of Numpy arrays, which are most commonly used in ML tasks.

## <font color='blue'>1. Basic Operations </font>


### <font style="color:rgb(8,133,37)">1.1. Python list to numpy array</font>

In [9]:
py_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

np_array = np.array(py_list)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
py_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

np_array= np.array(py_list)
np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### <font style="color:rgb(8,133,37)">1.2. Slicing and Indexing</font>

In [11]:
print('First row:\t\t\t{}'.format(np_array[0]))
print('First column:\t\t\t{}'.format(np_array[:, 0]))
print('3rd row 2nd column element:\t{}'.format(np_array[2][1]))
print('2nd onwards row and 2nd onwards column:\n{}'.format(np_array[1:, 1:]))
print('Last 2 rows and last 2 columns:\n{}'.format(np_array[-2:, -2:]))
print('Array with 3rd, 1st and 4th row:\n{}'.format(np_array[[2, 0, 3]]))

First row:			[1 2 3]
First column:			[ 1  4  7 10]
3rd row 2nd column element:	8
2nd onwards row and 2nd onwards column:
[[ 5  6]
 [ 8  9]
 [11 12]]
Last 2 rows and last 2 columns:
[[ 8  9]
 [11 12]]
Array with 3rd, 1st and 4th row:
[[ 7  8  9]
 [ 1  2  3]
 [10 11 12]]


### <font style="color:rgb(8,133,37)">1.3. Basic attributes of NumPy array</font>

Get a full list of attributes of an ndarray object [here](https://numpy.org/devdocs/user/quickstart.html).

In [12]:
print('Data type:\t{}'.format(np_array.dtype))
print('Array shape:\t{}'.format(np_array.shape))

Data type:	int32
Array shape:	(4, 3)


Let's create a function (with name `array_info`) to print the NumPy array, its shape, and its data type. We use this function to print arrays further in this section. 


In [13]:
def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}\n'.format(array.shape))
    
array_info(np_array)

Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Data type:	int32
Array shape:	(4, 3)



### <font style="color:rgb(8,133,37)">1.4. Creating NumPy array using built-in functions and datatypes</font>

The full list of supported data types can be found [here](https://numpy.org/devdocs/user/basics.types.html).


**Sequence Array**

`np.arange([start, ]stop, [step, ]dtype=None)`

Return evenly spaced values in `[start, stop)`.

More delatis of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html).

In [14]:
# sequence array
array = np.arange(10, dtype=np.int64)
array_info(array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)



In [15]:
# sequence array
array = np.arange(5, 10, dtype=np.float)
array_info(array)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [16]:
# sequence array
array = np.arange(5, 10, dtype=np.float64)
array_info(array)

Array:
[5. 6. 7. 8. 9.]
Data type:	float64
Array shape:	(5,)



**Zeroes Array**

In [17]:
# Zero array/matrix
zeros = np.zeros((2, 3), dtype=np.float32)
array_info(zeros)

Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Data type:	float32
Array shape:	(2, 3)



**Ones Array**

In [18]:
# ones array/matrix
ones = np.ones((3, 2), dtype=np.int8)
array_info(ones)

Array:
[[1 1]
 [1 1]
 [1 1]]
Data type:	int8
Array shape:	(3, 2)



**Constant Array**

In [19]:
# constant array/matrix
array = np.full((3, 3), 3.14)
array_info(array)

Array:
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
Data type:	float64
Array shape:	(3, 3)



**Identity Array**

In [20]:
# identity array/matrix
identity = np.eye(5, dtype=np.float32)      # identity matrix of shape 5x5
array_info(identity)

Array:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Data type:	float32
Array shape:	(5, 5)



**Random Integers Array**

`np.random.randint(low, high=None, size=None, dtype='l')`

Return random integer from the `discrete uniform` distribution in `[low, high)`. If high is `None`, then return elements are in `[0, low)`

More details can be found [here](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html).

In [21]:
# random integers array/matrix
rand_int = np.random.randint(5, 10, (2,3)) # random integer array of shape 2x3, values lies in [5, 10)
array_info(rand_int)

Array:
[[9 8 7]
 [7 8 7]]
Data type:	int32
Array shape:	(2, 3)



**Random Array**

`np.random.random(size=None)`

Results are from the `continuous uniform` distribution in `[0.0, 1.0)`.

These types of functions are useful is initializing the weight in Deep Learning. More details and similar functions can found [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.random.html).

In [22]:
# random array/matrix
random_array = np.random.random((5, 5))   # random array of shape 5x5
array_info(random_array)

Array:
[[0.00436435 0.66891513 0.83093149 0.21557436 0.07700012]
 [0.10421338 0.11911139 0.07386371 0.3725831  0.51311755]
 [0.65165976 0.99362184 0.06378068 0.52289495 0.8582803 ]
 [0.62709383 0.26434099 0.06397858 0.54885293 0.1389424 ]
 [0.72472797 0.16139215 0.69991412 0.08372542 0.47204638]]
Data type:	float64
Array shape:	(5, 5)



**Boolean Array**

If we compare above `random_array` with some `constant` or `array` of the same shape, we will get a boolean array.

In [23]:
# Boolean array/matrix
bool_array = random_array > 0.5
array_info(bool_array)

Array:
[[False  True  True False False]
 [False False False False  True]
 [ True  True False  True  True]
 [ True False False  True False]
 [ True False  True False False]]
Data type:	bool
Array shape:	(5, 5)



The boolean array can be used to get value from the array. If we use a boolean array of the same shape as indices, we will get those values for which the boolean array is True, and other values will be masked.

Let's use the above `boolen_array` to get values from `random_array`.

In [24]:
# Use boolean array/matrix to get values from array/matrix
values = random_array[bool_array]
array_info(values)

Array:
[0.66891513 0.83093149 0.51311755 0.65165976 0.99362184 0.52289495
 0.8582803  0.62709383 0.54885293 0.72472797 0.69991412]
Data type:	float64
Array shape:	(11,)



Basically, from the above method, we are filtering values that are greater than `0.5`. 

**Linespace**

`np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`

Returns num evenly spaced samples, calculated over the interval `[start, stop]`.

More detais about the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)

In [25]:
# Linspace
linespace = np.linspace(0, 5, 7, dtype=np.float32)   # 7 elements between 0 and 5
array_info(linespace)

Array:
[0.        0.8333333 1.6666666 2.5       3.3333333 4.1666665 5.       ]
Data type:	float32
Array shape:	(7,)



### <font style="color:rgb(8,133,37)">1.5. Data type conversion</font>

Sometimes it is essential to convert one data type to another data type.

In [26]:
age_in_years = np.random.randint(0, 100, 10)
array_info(age_in_years)

Array:
[84 24 16 55 54 62 19  9 15 29]
Data type:	int32
Array shape:	(10,)



Do we really need an `int64` data type to store age?

So let's convert it to `uint8`.

In [27]:
age_in_years = age_in_years.astype(np.uint8)
array_info(age_in_years)

Array:
[84 24 16 55 54 62 19  9 15 29]
Data type:	uint8
Array shape:	(10,)



Let's convert it to `float128`. 😜

In [29]:
age_in_years = age_in_years.astype(np.float128)
array_info(age_in_years)

AttributeError: module 'numpy' has no attribute 'float128'

In [30]:

age_in_years = age_in_years.astype(np.float64)
array_info(age_in_years)


Array:
[84. 24. 16. 55. 54. 62. 19.  9. 15. 29.]
Data type:	float64
Array shape:	(10,)



## <font color='blue'>2. Mathematical functions </font>

Numpy supports a lot of Mathematical operations with array/matrix. Here we will see a few of them which are useful in Deep Learning. All supported functions can be found [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html).

### <font style="color:rgb(8,133,37)">2.1. Exponential Function </font>
Exponential functions ( also called `exp` ) are used in neural networks as activations functions. They are used in softmax functions which is widely used in Classification tasks.

Return element-wise `exponential` of `array`.

More details of `np.exp` can be found **[here](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.exp.html#numpy.exp)**

In [31]:
array = np.array([np.full(3, -1), np.zeros(3), np.ones(3)])
array_info(array)

# exponential of a array/matrix
print('Exponential of an array:')
exp_array = np.exp(array)
array_info(exp_array)

Array:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
Data type:	float64
Array shape:	(3, 3)

Exponential of an array:
Array:
[[0.36787944 0.36787944 0.36787944]
 [1.         1.         1.        ]
 [2.71828183 2.71828183 2.71828183]]
Data type:	float64
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">2.2. Square Root </font>

`np.sqrt` return the element-wise `square-root` (`non-negative`) of an array.

More details of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html)

`Root Mean Square Error` (`RMSE`) and `Mean Absolute Error` (`MAE`) commonly used to measure the `accuracy` of continuous variables.

In [32]:
array = np.arange(10)
array_info(array)

print('Square root:')
root_array = np.sqrt(array)
array_info(root_array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int32
Array shape:	(10,)

Square root:
Array:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Data type:	float64
Array shape:	(10,)



### <font style="color:rgb(8,133,37)">2.3. Logrithm </font>

`np.log` return element-wise natural logrithm of an array.

More details of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html)

`Cross-Entropy` / `log loss` is the most commonly used loss in Machine Learning classification problem. 

In [33]:
array = np.array([0, np.e, np.e**2, 1, 10])
array_info(array)

print('Logrithm:')
log_array = np.log(array)
array_info(log_array)

Array:
[ 0.          2.71828183  7.3890561   1.         10.        ]
Data type:	float64
Array shape:	(5,)

Logrithm:
Array:
[      -inf 1.         2.         0.         2.30258509]
Data type:	float64
Array shape:	(5,)



C:\Users\lenovo\AppData\Local\Temp\ipykernel_67216\4157081557.py:5: RuntimeWarning: divide by zero encountered in log
  log_array = np.log(array)


<font color='red'>**Note:** Getting warning because we are trying to calculate `log(0)`.</font>

### <font style="color:rgb(8,133,37)">2.4. Power </font>

`numpy.power(x1, x2)`

Returns first array elements raised to powers from second array, element-wise.

Second array must be broadcastable to first array.

What is **broadcasting**? We will see later.

More detalis about the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html)

In [34]:
array = np.arange(0, 6, dtype=np.int64)
array_info(array)

print('Power 3:')
pow_array = np.power(array, 3)
array_info(pow_array)

Array:
[0 1 2 3 4 5]
Data type:	int64
Array shape:	(6,)

Power 3:
Array:
[  0   1   8  27  64 125]
Data type:	int64
Array shape:	(6,)



### <font style="color:rgb(8,133,37)">2.5. Clip Values </font>

`np.clip(a, a_min, a_max)`

Return element-wise cliped values between `a_min` and `a_max`.

More details of the finction can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html)

`Rectified Linear Unit` (`ReLU`) is the most commonly used activation function in Deep Learning.

What ReLU do?

If the value is less than zero, it makes it zero otherwise leave as it is. In NumPy assignment will be implementing this activation function using NumPy.

In [35]:
array = np.random.random((3, 3))
array_info(array)

# clipped between 0.2 and 0.5
print('Clipped between 0.2 and 0.5')
cliped_array = np.clip(array, 0.2, 0.5)
array_info(cliped_array)

# clipped to 0.2
print('Clipped to 0.2')
cliped_array = np.clip(array, 0.2, np.inf)
array_info(cliped_array)

Array:
[[0.31225389 0.87474754 0.14683127]
 [0.48987649 0.32887883 0.00392581]
 [0.12275731 0.40732156 0.85476875]]
Data type:	float64
Array shape:	(3, 3)

Clipped between 0.2 and 0.5
Array:
[[0.31225389 0.5        0.2       ]
 [0.48987649 0.32887883 0.2       ]
 [0.2        0.40732156 0.5       ]]
Data type:	float64
Array shape:	(3, 3)

Clipped to 0.2
Array:
[[0.31225389 0.87474754 0.2       ]
 [0.48987649 0.32887883 0.2       ]
 [0.2        0.40732156 0.85476875]]
Data type:	float64
Array shape:	(3, 3)



## <font color='blue'>3. Reshape ndarray </font>

Reshaping the array / matrix is very often required in Machine Learning and Computer vision. 

### <font style="color:rgb(8,133,37)">3.1. Reshape </font>

`np.reshape` gives an array in new shape, without changing its data.

More details of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

In [37]:
a = np.arange(1, 10, dtype=np.int32)
array_info(a)

print('Reshape to 3x3:')
a_3x3 = a.reshape(3, 3)
array_info(a_3x3)

print('Reshape 3x3 to 3x3x1:')
a_3x3x1 = a_3x3.reshape(3, 3, 1)
array_info(a_3x3x1)

Array:
[1 2 3 4 5 6 7 8 9]
Data type:	int32
Array shape:	(9,)

Reshape to 3x3:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int32
Array shape:	(3, 3)

Reshape 3x3 to 3x3x1:
Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Data type:	int32
Array shape:	(3, 3, 1)



### <font style="color:rgb(8,133,37)">3.2. Expand Dim </font>

`np.expand_dims`

In the last reshape, we have added a new axis. We can use `np.expand_dims` or `np.newaxis` to do the same thing.

Mode details for `np.expand_dim` can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html)

In [38]:
print('Using np.expand_dims:')
a_expand = np.expand_dims(a_3x3, axis=2)
array_info(a_expand)

print('Using np.newaxis:')
a_newaxis = a_3x3[..., np.newaxis]
# or 
# a_newaxis = a_3x3[:, :, np.newaxis]
array_info(a_newaxis)

Using np.expand_dims:
Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Data type:	int32
Array shape:	(3, 3, 1)

Using np.newaxis:
Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Data type:	int32
Array shape:	(3, 3, 1)



### <font style="color:rgb(8,133,37)">3.3. Squeeze </font>

Sometimes we need to remove the redundant axis (single-dimensional entries). We can use `np.squeeze` to do this.

More details of `np.squeeze` can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html)

Deep Learning very often uses this functionality.

In [39]:
print('Squeeze along axis=2:')
a_squeezed = np.squeeze(a_newaxis, axis=2)
array_info(a_squeezed)

# should get value error
print('Squeeze along axis=1, should get ValueError')
a_squeezed_error = np.squeeze(a_newaxis, axis=1)  # Getting error because of the size of 
                                                  # axis-1 is not equal to one.

Squeeze along axis=2:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int32
Array shape:	(3, 3)

Squeeze along axis=1, should get ValueError


ValueError: cannot select an axis to squeeze out which has size not equal to one

<font color='red'>**Note:** Getting error because of the size of axis-1 is not equal to one.</font>

### <font style="color:rgb(8,133,37)">3.4. Reshape revisit </font>

We have a 1-d array of length n. We want to reshape in a 2-d array such that the number of columns becomes two, and we do not care about the number of rows. 

In [40]:
a = np.arange(10)
array_info(a)

print('Reshape such that number of column is 2:')
a_col_2 = a.reshape(-1, 2)
array_info(a_col_2)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int32
Array shape:	(10,)

Reshape such that number of column is 2:
Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Data type:	int32
Array shape:	(5, 2)



## <font color='blue'>4. Combine Arrays / Matrix </font>

Combining two or more arrays is a frequent operation in machine learning. Let's have a look at a few methods. 


### <font style="color:rgb(8,133,37)">4.1. Concatenate </font>

`np.concatenate`, Join a sequence of arrays along an existing axis.

More details of the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)

In [41]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9]])

print('Concatenate along axis zero:')
array = np.concatenate((a1, a2), axis=0)
array_info(array)

Concatenate along axis zero:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int32
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">4.2. hstack </font>

`np.hstack`, stack arrays in sequence horizontally (column-wise).

More details of the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack)

In [42]:
a1 = np.array((1, 2, 3))
a2 = np.array((4, 5, 6))
a_hstacked = np.hstack((a1,a2))

print('Horizontal stack:')
array_info(a_hstacked)

Horizontal stack:
Array:
[1 2 3 4 5 6]
Data type:	int32
Array shape:	(6,)



In [43]:
a1 = np.array([[1],[2],[3]])
a2 = np.array([[4],[5],[6]])
a_hstacked = np.hstack((a1,a2))

print('Horizontal stack:')
array_info(a_hstacked)

Horizontal stack:
Array:
[[1 4]
 [2 5]
 [3 6]]
Data type:	int32
Array shape:	(3, 2)



### <font style="color:rgb(8,133,37)">4.3. vstack </font>

`np.vstack`, tack arrays in sequence vertically (row-wise).

More details of the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html#numpy.vstack)

In [44]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a_vstacked = np.vstack((a1, a2))

print('Vertical stack:')
array_info(a_vstacked)

Vertical stack:
Array:
[[1 2 3]
 [4 5 6]]
Data type:	int32
Array shape:	(2, 3)



In [45]:
a1 = np.array([[1, 11], [2, 22], [3, 33]])
a2 = np.array([[4, 44], [5, 55], [6, 66]])
a_vstacked = np.vstack((a1, a2))

print('Vertical stack:')
array_info(a_vstacked)

Vertical stack:
Array:
[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]
Data type:	int32
Array shape:	(6, 2)



## <font color='blue'>5. Element wise Operations </font>


Let's generate a random number to show element-wise operations. 

In [46]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.32816557 0.43684979 0.16821164 0.58901018]
 [0.76609366 0.92566894 0.70792056 0.00776044]
 [0.75381916 0.79447991 0.5538804  0.45151969]
 [0.5951816  0.54842201 0.2114941  0.76759895]]
Data type:	float64
Array shape:	(4, 4)

Array:
[[0.5918957  0.69960611 0.04243233 0.2208744 ]
 [0.3513185  0.20564235 0.47352416 0.89484894]
 [0.90331524 0.40714411 0.25029034 0.68777362]
 [0.93358588 0.341024   0.9263071  0.69860995]]
Data type:	float64
Array shape:	(4, 4)



### <font style="color:rgb(8,133,37)">5.1. Element wise Scalar Operation </font>

**Scalar Addition**

In [47]:
a + 5 # element wise scalar addition

array([[5.32816557, 5.43684979, 5.16821164, 5.58901018],
       [5.76609366, 5.92566894, 5.70792056, 5.00776044],
       [5.75381916, 5.79447991, 5.5538804 , 5.45151969],
       [5.5951816 , 5.54842201, 5.2114941 , 5.76759895]])

**Scalar Subtraction**

In [48]:
a - 5 # element wise scalar subtraction

array([[-4.67183443, -4.56315021, -4.83178836, -4.41098982],
       [-4.23390634, -4.07433106, -4.29207944, -4.99223956],
       [-4.24618084, -4.20552009, -4.4461196 , -4.54848031],
       [-4.4048184 , -4.45157799, -4.7885059 , -4.23240105]])


**Scalar Multiplication**

In [49]:
a * 10 # element wise scalar multiplication

array([[3.28165574, 4.3684979 , 1.68211644, 5.89010179],
       [7.66093664, 9.25668942, 7.07920561, 0.07760439],
       [7.5381916 , 7.94479909, 5.53880402, 4.51519695],
       [5.951816  , 5.4842201 , 2.11494098, 7.67598952]])

**Scalar Division**

In [50]:
a/10 # element wise scalar division

array([[0.03281656, 0.04368498, 0.01682116, 0.05890102],
       [0.07660937, 0.09256689, 0.07079206, 0.00077604],
       [0.07538192, 0.07944799, 0.05538804, 0.04515197],
       [0.05951816, 0.0548422 , 0.02114941, 0.0767599 ]])

### <font style="color:rgb(8,133,37)">5.2. Element wise Array Operations </font>

**Arrays Addition**

In [51]:
a + b # element wise array/vector addition

array([[0.92006128, 1.1364559 , 0.21064397, 0.80988458],
       [1.11741216, 1.13131129, 1.18144472, 0.90260938],
       [1.6571344 , 1.20162402, 0.80417074, 1.13929332],
       [1.52876748, 0.88944601, 1.1378012 , 1.4662089 ]])

**Arrays Subtraction**

In [52]:
a - b # element wise array/vector subtraction

array([[-0.26373013, -0.26275632,  0.12577932,  0.36813578],
       [ 0.41477516,  0.72002659,  0.2343964 , -0.88708851],
       [-0.14949608,  0.3873358 ,  0.30359006, -0.23625393],
       [-0.33840428,  0.20739801, -0.714813  ,  0.068989  ]])

**Arrays Multiplication**

In [53]:
a * b # element wise array/vector multiplication

array([[0.19423979, 0.30562278, 0.00713761, 0.13009727],
       [0.26914288, 0.19035674, 0.33521749, 0.00694442],
       [0.68093634, 0.32346781, 0.13863092, 0.31054334],
       [0.55565314, 0.18702507, 0.19590848, 0.53625227]])

**Arrays Division**

In [54]:
a / b # element wise array/vector division

array([[0.55443142, 0.62442249, 3.96423335, 2.66672002],
       [2.18062431, 4.50135362, 1.49500411, 0.00867235],
       [0.83450287, 1.95134816, 2.21295156, 0.65649464],
       [0.63752207, 1.60816252, 0.22831963, 1.09875181]])

We can notice that the dimension of both arrays is equal in above arrays element-wise operations. **What if dimensions are not equal.** Let's check!!

In [55]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 2)
array_info(c)
# Should throw ValueError
a + c

Array "a":
Array:
[[0.32816557 0.43684979 0.16821164 0.58901018]
 [0.76609366 0.92566894 0.70792056 0.00776044]
 [0.75381916 0.79447991 0.5538804  0.45151969]
 [0.5951816  0.54842201 0.2114941  0.76759895]]
Data type:	float64
Array shape:	(4, 4)

Array "c":
Array:
[[0.41253981 0.44479972]
 [0.19592511 0.34573115]]
Data type:	float64
Array shape:	(2, 2)



ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

<font color='red'>**Oh got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)` 

**Let's see it next.**


### <font style="color:rgb(8,133,37)">5.3. Broadcasting </font>

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array. 

Let's try to understand with a simple example.

In [56]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a+b)  # b is reshaped such that it can be added to a.


# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int32
Array shape:	(3, 3)

Array "b":
Array:
[0 1 0]
Data type:	int32
Array shape:	(3,)

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int32
Array shape:	(3, 3)



## <font color='blue'>6. Linear Algebra</font>

Here we see commonly use linear algebra operations in Machine Learning. 

### <font style="color:rgb(8,133,37)">6.1. Transpose </font>

In [57]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()
array_info(a_transpose)

Array "a":
Array:
[[0.47795217 0.99901192 0.36094509]
 [0.19775632 0.50548641 0.69087847]]
Data type:	float64
Array shape:	(2, 3)

Transose of "a":
Array:
[[0.47795217 0.19775632]
 [0.99901192 0.50548641]
 [0.36094509 0.69087847]]
Data type:	float64
Array shape:	(3, 2)



### <font style="color:rgb(8,133,37)">6.2. Matrix Multiplication</font>
We will discuss 2 ways of performing Matrix Multiplication.

- `matmul`
- Python `@` operator

**Using matmul function in numpy**
This is the most used approach for multiplying two matrices using Numpy. [See docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html)

In [58]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

c = np.matmul(a,b) # matrix multiplication of a and b

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim1 of a and dim0 of b has to be 
                                                        # same for matrix multiplication

Array "a":
Array:
[[0.99118136 0.84565264 0.58055308 0.78786818]
 [0.03877729 0.61587709 0.81651247 0.50688196]
 [0.19955518 0.86385662 0.55700172 0.14314388]]
Data type:	float64
Array shape:	(3, 4)

Array "b"
Array:
[[0.39127937 0.99072935]
 [0.93264833 0.12269033]
 [0.80574681 0.69142565]
 [0.76782727 0.58965841]]
Data type:	float64
Array shape:	(4, 2)

matrix multiplication of a and b:
Array:
[[2.24925081 1.95172826]
 [1.63666961 0.97742484]
 [1.44246839 0.77322329]]
Data type:	float64
Array shape:	(3, 2)

(3, 4) x (4, 2) --> (3, 2)


**Using `@` operator**
This method of multiplication was introduced in Python 3.5. [See docs](https://www.python.org/dev/peps/pep-0465/)

In [59]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

c = a@b # matrix multiplication of a and b
array_info(c)

Array "a":
Array:
[[0.79891614 0.63338517 0.25669594 0.35424661]
 [0.08160609 0.79793695 0.45860528 0.54518533]
 [0.0354825  0.43671303 0.10788505 0.67901018]]
Data type:	float64
Array shape:	(3, 4)

Array "b"
Array:
[[0.59659238 0.086633  ]
 [0.32487048 0.83472674]
 [0.42353124 0.41733203]
 [0.92809682 0.83567253]]
Data type:	float64
Array shape:	(4, 2)

Array:
[[1.11988933 1.00107764]
 [1.00813016 1.32011616]
 [0.83892364 0.98006404]]
Data type:	float64
Array shape:	(3, 2)



### <font style="color:rgb(8,133,37)">6.3. Inverse</font>

In [60]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)
A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.52288724 0.18483231 0.82026691]
 [0.37048096 0.09302743 0.71300384]
 [0.88409056 0.96994519 0.6181323 ]]
Data type:	float64
Array shape:	(3, 3)

Inverse of "A" ("A_inverse"):
Array:
[[ 21.08828896 -22.66114321  -1.84514487]
 [-13.34843879  13.36915978   2.29242262]
 [ -9.21599344  11.43307118   0.65964985]]
Data type:	float64
Array shape:	(3, 3)

"A x A_inverse = Identity" should be true:
Array:
[[ 1.00000000e+00 -1.32089183e-15 -1.61993573e-16]
 [ 7.82755088e-17  1.00000000e+00 -1.44249695e-16]
 [-3.35902354e-15  3.08913306e-15  1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">6.4. Dot Product</font>

In [61]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

dot_pro = np.dot(a, b)  # It will be a scalar, so its shape will be empty
array_info(dot_pro)

Array:
70
Data type:	int32
Array shape:	()



## <font color='blue'>7. Array statistics</font>

### <font style="color:rgb(8,133,37)">7.1. Sum</font>

In [62]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### <font style="color:rgb(8,133,37)">7.2. Sum along Axis</font>

In [63]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('')

print('sum along 0th axis = ',a.sum(axis = 0)) # sum along 0th axis ie: 1+4, 2+5, 3+6
print("")
print('sum along 1st axis = ',a.sum(axis = 1)) # sum along 1st axis ie: 1+2+3, 4+5+6

[[1 2 3]
 [4 5 6]]

sum along 0th axis =  [5 7 9]

sum along 1st axis =  [ 6 15]


### <font style="color:rgb(8,133,37)">7.3. Minimum and Maximum</font>

In [64]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### <font style="color:rgb(8,133,37)">7.4. Min and Max along Axis</font>

In [65]:
a = np.array([[-2, 0, 2], [1, 2, 3]])

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

a =
 [[-2  0  2]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  3

Minimum along axis 0 =  [-2  0  2]
Maximum along axis 0 =  [1 2 3]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [2 3]


### <font style="color:rgb(8,133,37)">7.5. Mean and Standard Deviation</font>

In [66]:
a = np.array([-1, 0, -0.4, 1.2, 1.43, -1.9, 0.66])

print('mean of the array = ',a.mean())
print('standard deviation of the array = ',a.std())

mean of the array =  -0.001428571428571414
standard deviation of the array =  1.1142252730860458


### <font style="color:rgb(8,133,37)">7.6. Standardizing the Array</font>

Make distribution of array elements such that`mean=0` and `std=1`.

In [67]:
a = np.array([-1, 0, -0.4, 1.2, 1.43, -1.9, 0.66])

print('mean of the array = ',a.mean())
print('standard deviation of the array = ',a.std())
print()

standardized_a = (a - a.mean())/a.std()
print('Standardized Array = ', standardized_a)
print()

print('mean of the standardized array = ',standardized_a.mean()) # close to 0
print('standard deviation of the standardized  array = ',standardized_a.std()) # equals to 1

mean of the array =  -0.001428571428571414
standard deviation of the array =  1.1142252730860458

Standardized Array =  [-8.96202458e-01  1.28212083e-03 -3.57711711e-01  1.07826362e+00
  1.28468507e+00 -1.70393858e+00  5.93621943e-01]

mean of the standardized array =  -3.172065784643304e-17
standard deviation of the standardized  array =  1.0


# <font color='blue'>References </font>

https://numpy.org/devdocs/user/quickstart.html

https://numpy.org/devdocs/user/basics.types.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

https://coolsymbol.com/emojis/emoji-for-copy-and-paste.html

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.exp.html#numpy.exp

https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack

https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html#numpy.vstack